package cn.edu.bjtu.vo;

// Generated 2015-2-24 14:26:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Assessform generated by hbm2java
 */
@Component
public class Assessform implements java.io.Serializable {

	private String id;
	private String clientId;
	private Date relDate;
	private String orderId;
	private Integer serviceAttitude;
	private Integer transportEfficiency;
	private Integer cargoSafety;
	private Integer totalMoney;
	private String comment;
	private Integer linetransport;
	private Integer cityline;
	private Integer car;
	private Integer warehouse;

	public Assessform() {
	}

	public Assessform(String id) {
		this.id = id;
	}

	public Assessform(String id, String clientId, Date relDate, String orderId,
			Integer serviceAttitude, Integer transportEfficiency,
			Integer cargoSafety, Integer totalMoney, String comment,
			Integer linetransport, Integer cityline, Integer car,
			Integer warehouse) {
		this.id = id;
		this.clientId = clientId;
		this.relDate = relDate;
		this.orderId = orderId;
		this.serviceAttitude = serviceAttitude;
		this.transportEfficiency = transportEfficiency;
		this.cargoSafety = cargoSafety;
		this.totalMoney = totalMoney;
		this.comment = comment;
		this.linetransport = linetransport;
		this.cityline = cityline;
		this.car = car;
		this.warehouse = warehouse;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Integer getServiceAttitude() {
		return this.serviceAttitude;
	}

	public void setServiceAttitude(Integer serviceAttitude) {
		this.serviceAttitude = serviceAttitude;
	}

	public Integer getTransportEfficiency() {
		return this.transportEfficiency;
	}

	public void setTransportEfficiency(Integer transportEfficiency) {
		this.transportEfficiency = transportEfficiency;
	}

	public Integer getCargoSafety() {
		return this.cargoSafety;
	}

	public void setCargoSafety(Integer cargoSafety) {
		this.cargoSafety = cargoSafety;
	}

	public Integer getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(Integer totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getLinetransport() {
		return this.linetransport;
	}

	public void setLinetransport(Integer linetransport) {
		this.linetransport = linetransport;
	}

	public Integer getCityline() {
		return this.cityline;
	}

	public void setCityline(Integer cityline) {
		this.cityline = cityline;
	}

	public Integer getCar() {
		return this.car;
	}

	public void setCar(Integer car) {
		this.car = car;
	}

	public Integer getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Integer warehouse) {
		this.warehouse = warehouse;
	}

}
