package cn.edu.bjtu.vo;

import java.util.Date;

import org.springframework.stereotype.Component;

// Generated 2015-3-3 13:57:50 by Hibernate Tools 3.4.0.CR1

/**
 * Businessclient generated by hbm2java
 */
@Component
public class Businessclient implements java.io.Serializable {

	private String id;
	private String clientName;
	private String clientBusiness;
	private String contact;
	private String phone;
	private String relatedMaterial;
	private String remarks;
	private String carrierId;
	private String account;
	private Date relDate;

	public Businessclient() {
	}

	public Businessclient(String id) {
		this.id = id;
	}

	

	public Businessclient(String id, String clientName, String clientBusiness,
			String contact, String phone, String relatedMaterial,
			String remarks, String carrierId, String account, Date relDate) {
		super();
		this.id = id;
		this.clientName = clientName;
		this.clientBusiness = clientBusiness;
		this.contact = contact;
		this.phone = phone;
		this.relatedMaterial = relatedMaterial;
		this.remarks = remarks;
		this.carrierId = carrierId;
		this.account = account;
		this.relDate = relDate;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public Date getRelDate() {
		return relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientBusiness() {
		return this.clientBusiness;
	}

	public void setClientBusiness(String clientBusiness) {
		this.clientBusiness = clientBusiness;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRelatedMaterial() {
		return this.relatedMaterial;
	}

	public void setRelatedMaterial(String relatedMaterial) {
		this.relatedMaterial = relatedMaterial;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

}
