package cn.edu.bjtu.vo;

// Generated 2015-2-22 16:45:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * CarCarrierViewId generated by hbm2java
 */
@Component
public class CarCarrierView implements java.io.Serializable {

	private String carLength;
	private String carNum;
	private String carTeam;
	private String carUse;
	private String carLocation;
	private Date relDate;
	private String carType;
	private String linetransportId;
	private Double locLongitude;
	private Double locLatitude;
	private String locationType;
	private String carBrand;
	private String storage;
	private String carrierId;
	private String carWeight;
	private String carState;
	private String driverId;
	private Date purchaseTime;
	private String id;
	private String companyName;
	private String carBase;
	
	public CarCarrierView() {
	}

	public CarCarrierView(String id) {
		this.id = id;
	}

	public CarCarrierView(String carLength, String carNum, String carTeam,
			String carUse, String carLocation, Date relDate, String carType,
			String linetransportId, Double locLongitude, Double locLatitude,
			String locationType, String carBrand, String storage,
			String carrierId, String carWeight, String carState,
			String driverId, Date purchaseTime, String id, String companyName, String carBase) {
		this.carLength = carLength;
		this.carNum = carNum;
		this.carTeam = carTeam;
		this.carUse = carUse;
		this.carLocation = carLocation;
		this.relDate = relDate;
		this.carType = carType;
		this.linetransportId = linetransportId;
		this.locLongitude = locLongitude;
		this.locLatitude = locLatitude;
		this.locationType = locationType;
		this.carBrand = carBrand;
		this.storage = storage;
		this.carrierId = carrierId;
		this.carWeight = carWeight;
		this.carState = carState;
		this.driverId = driverId;
		this.purchaseTime = purchaseTime;
		this.id = id;
		this.companyName = companyName;
		this.carBase = carBase;
	}

	public String getCarLength() {
		return this.carLength;
	}

	public void setCarLength(String carLength) {
		this.carLength = carLength;
	}

	public String getCarNum() {
		return this.carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	public String getCarTeam() {
		return this.carTeam;
	}

	public void setCarTeam(String carTeam) {
		this.carTeam = carTeam;
	}

	public String getCarUse() {
		return this.carUse;
	}

	public void setCarUse(String carUse) {
		this.carUse = carUse;
	}

	public String getCarLocation() {
		return this.carLocation;
	}

	public void setCarLocation(String carLocation) {
		this.carLocation = carLocation;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	public String getLinetransportId() {
		return this.linetransportId;
	}

	public void setLinetransportId(String linetransportId) {
		this.linetransportId = linetransportId;
	}

	public Double getLocLongitude() {
		return this.locLongitude;
	}

	public void setLocLongitude(Double locLongitude) {
		this.locLongitude = locLongitude;
	}

	public Double getLocLatitude() {
		return this.locLatitude;
	}

	public void setLocLatitude(Double locLatitude) {
		this.locLatitude = locLatitude;
	}

	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	public String getCarBrand() {
		return this.carBrand;
	}

	public void setCarBrand(String carBrand) {
		this.carBrand = carBrand;
	}

	public String getStorage() {
		return this.storage;
	}

	public void setStorage(String storage) {
		this.storage = storage;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public String getCarWeight() {
		return this.carWeight;
	}

	public void setCarWeight(String carWeight) {
		this.carWeight = carWeight;
	}

	public String getCarState() {
		return this.carState;
	}

	public void setCarState(String carState) {
		this.carState = carState;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public Date getPurchaseTime() {
		return this.purchaseTime;
	}

	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getCarBase() {
		return this.carBase;
	}

	public void setCarBase(String carBase) {
		this.carBase = carBase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarCarrierView))
			return false;
		CarCarrierView castOther = (CarCarrierView) other;

		return ((this.getCarLength() == castOther.getCarLength()) || (this
				.getCarLength() != null && castOther.getCarLength() != null && this
				.getCarLength().equals(castOther.getCarLength())))
				&& ((this.getCarNum() == castOther.getCarNum()) || (this
						.getCarNum() != null && castOther.getCarNum() != null && this
						.getCarNum().equals(castOther.getCarNum())))
				&& ((this.getCarTeam() == castOther.getCarTeam()) || (this
						.getCarTeam() != null && castOther.getCarTeam() != null && this
						.getCarTeam().equals(castOther.getCarTeam())))
				&& ((this.getCarUse() == castOther.getCarUse()) || (this
						.getCarUse() != null && castOther.getCarUse() != null && this
						.getCarUse().equals(castOther.getCarUse())))
				&& ((this.getCarLocation() == castOther.getCarLocation()) || (this
						.getCarLocation() != null
						&& castOther.getCarLocation() != null && this
						.getCarLocation().equals(castOther.getCarLocation())))
				&& ((this.getRelDate() == castOther.getRelDate()) || (this
						.getRelDate() != null && castOther.getRelDate() != null && this
						.getRelDate().equals(castOther.getRelDate())))
				&& ((this.getCarType() == castOther.getCarType()) || (this
						.getCarType() != null && castOther.getCarType() != null && this
						.getCarType().equals(castOther.getCarType())))
				&& ((this.getLinetransportId() == castOther
						.getLinetransportId()) || (this.getLinetransportId() != null
						&& castOther.getLinetransportId() != null && this
						.getLinetransportId().equals(
								castOther.getLinetransportId())))
				&& ((this.getLocLongitude() == castOther.getLocLongitude()) || (this
						.getLocLongitude() != null
						&& castOther.getLocLongitude() != null && this
						.getLocLongitude().equals(castOther.getLocLongitude())))
				&& ((this.getLocLatitude() == castOther.getLocLatitude()) || (this
						.getLocLatitude() != null
						&& castOther.getLocLatitude() != null && this
						.getLocLatitude().equals(castOther.getLocLatitude())))
				&& ((this.getLocationType() == castOther.getLocationType()) || (this
						.getLocationType() != null
						&& castOther.getLocationType() != null && this
						.getLocationType().equals(castOther.getLocationType())))
				&& ((this.getCarBrand() == castOther.getCarBrand()) || (this
						.getCarBrand() != null
						&& castOther.getCarBrand() != null && this
						.getCarBrand().equals(castOther.getCarBrand())))
				&& ((this.getStorage() == castOther.getStorage()) || (this
						.getStorage() != null && castOther.getStorage() != null && this
						.getStorage().equals(castOther.getStorage())))
				&& ((this.getCarrierId() == castOther.getCarrierId()) || (this
						.getCarrierId() != null
						&& castOther.getCarrierId() != null && this
						.getCarrierId().equals(castOther.getCarrierId())))
				&& ((this.getCarWeight() == castOther.getCarWeight()) || (this
						.getCarWeight() != null
						&& castOther.getCarWeight() != null && this
						.getCarWeight().equals(castOther.getCarWeight())))
				&& ((this.getCarState() == castOther.getCarState()) || (this
						.getCarState() != null
						&& castOther.getCarState() != null && this
						.getCarState().equals(castOther.getCarState())))
				&& ((this.getDriverId() == castOther.getDriverId()) || (this
						.getDriverId() != null
						&& castOther.getDriverId() != null && this
						.getDriverId().equals(castOther.getDriverId())))
				&& ((this.getPurchaseTime() == castOther.getPurchaseTime()) || (this
						.getPurchaseTime() != null
						&& castOther.getPurchaseTime() != null && this
						.getPurchaseTime().equals(castOther.getPurchaseTime())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getCompanyName() == castOther.getCompanyName()) || (this
						.getCompanyName() != null
						&& castOther.getCompanyName() != null && this
						.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getCarBase() == castOther.getCarBase()) || (this
						.getCarBase() != null
						&& castOther.getCarBase() != null && this
						.getCarBase().equals(castOther.getCarBase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCarLength() == null ? 0 : this.getCarLength().hashCode());
		result = 37 * result
				+ (getCarNum() == null ? 0 : this.getCarNum().hashCode());
		result = 37 * result
				+ (getCarTeam() == null ? 0 : this.getCarTeam().hashCode());
		result = 37 * result
				+ (getCarUse() == null ? 0 : this.getCarUse().hashCode());
		result = 37
				* result
				+ (getCarLocation() == null ? 0 : this.getCarLocation()
						.hashCode());
		result = 37 * result
				+ (getRelDate() == null ? 0 : this.getRelDate().hashCode());
		result = 37 * result
				+ (getCarType() == null ? 0 : this.getCarType().hashCode());
		result = 37
				* result
				+ (getLinetransportId() == null ? 0 : this.getLinetransportId()
						.hashCode());
		result = 37
				* result
				+ (getLocLongitude() == null ? 0 : this.getLocLongitude()
						.hashCode());
		result = 37
				* result
				+ (getLocLatitude() == null ? 0 : this.getLocLatitude()
						.hashCode());
		result = 37
				* result
				+ (getLocationType() == null ? 0 : this.getLocationType()
						.hashCode());
		result = 37 * result
				+ (getCarBrand() == null ? 0 : this.getCarBrand().hashCode());
		result = 37 * result
				+ (getStorage() == null ? 0 : this.getStorage().hashCode());
		result = 37 * result
				+ (getCarrierId() == null ? 0 : this.getCarrierId().hashCode());
		result = 37 * result
				+ (getCarWeight() == null ? 0 : this.getCarWeight().hashCode());
		result = 37 * result
				+ (getCarState() == null ? 0 : this.getCarState().hashCode());
		result = 37 * result
				+ (getDriverId() == null ? 0 : this.getDriverId().hashCode());
		result = 37
				* result
				+ (getPurchaseTime() == null ? 0 : this.getPurchaseTime()
						.hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getCompanyName() == null ? 0 : this.getCompanyName()
						.hashCode());
		result = 37
				* result
				+ (getCarBase() == null ? 0 : this.getCarBase()
						.hashCode());
		return result;
	}

}
