package cn.edu.bjtu.vo;

// Generated 2015-2-22 16:45:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Carinfo generated by hbm2java
 */
@Component
public class Carinfo implements java.io.Serializable {

	private String id;
	private String carNum;
	private String carTeam;
	private String carUse;
	private Double carLength;
	private Double carWidth;
	private Double carHeight;
	private Double carWeight;
	private String carBase;
	private String terminalId;

	private String carState;
	private String carLocation;
	private Date relDate;
	private String carType;
	private String linetransportId;
	private Double locLongitude;
	private Double locLatitude;
	private String locationType;
	private Date purchaseTime;
	private String driverId;
	private String carBrand;
	private String storage;
	private String carrierId;
	private String stopPlace;

	public Carinfo() {
	}

	public Carinfo(String id) {
		this.id = id;
	}
	
	


	public Carinfo(String id, String carNum, String carTeam, String carUse,
			Double carLength, Double carWidth, Double carHeight,
			Double carWeight, String carBase, String terminalId,
			String carState, String carLocation, Date relDate, String carType,
			String linetransportId, Double locLongitude, Double locLatitude,
			String locationType, Date purchaseTime, String driverId,
			String carBrand, String storage, String carrierId, String stopPlace) {
		super();
		this.id = id;
		this.carNum = carNum;
		this.carTeam = carTeam;
		this.carUse = carUse;
		this.carLength = carLength;
		this.carWidth = carWidth;
		this.carHeight = carHeight;
		this.carWeight = carWeight;
		this.carBase = carBase;
		this.terminalId = terminalId;
		this.carState = carState;
		this.carLocation = carLocation;
		this.relDate = relDate;
		this.carType = carType;
		this.linetransportId = linetransportId;
		this.locLongitude = locLongitude;
		this.locLatitude = locLatitude;
		this.locationType = locationType;
		this.purchaseTime = purchaseTime;
		this.driverId = driverId;
		this.carBrand = carBrand;
		this.storage = storage;
		this.carrierId = carrierId;
		this.stopPlace = stopPlace;
	}
	
	public String getStopPlace() {
		return stopPlace;
	}

	public void setStopPlace(String stopPlace) {
		this.stopPlace = stopPlace;
	}

	public String getCarBase() {
		return carBase;
	}

	public void setCarBase(String carBase) {
		this.carBase = carBase;
	}
	
	public Double getCarLength() {
		return carLength;
	}

	public void setCarLength(Double carLength) {
		this.carLength = carLength;
	}

	public Double getCarWidth() {
		return carWidth;
	}

	public void setCarWidth(Double carWidth) {
		this.carWidth = carWidth;
	}

	public Double getCarHeight() {
		return carHeight;
	}

	public void setCarHeight(Double carHeight) {
		this.carHeight = carHeight;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCarNum() {
		return this.carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	public String getCarTeam() {
		return this.carTeam;
	}

	public void setCarTeam(String carTeam) {
		this.carTeam = carTeam;
	}

	public String getCarUse() {
		return this.carUse;
	}

	public void setCarUse(String carUse) {
		this.carUse = carUse;
	}

	

	public Double getCarWeight() {
		return carWeight;
	}

	public void setCarWeight(Double carWeight) {
		this.carWeight = carWeight;
	}

	public String getCarState() {
		return this.carState;
	}

	public void setCarState(String carState) {
		this.carState = carState;
	}

	public String getCarLocation() {
		return this.carLocation;
	}

	public void setCarLocation(String carLocation) {
		this.carLocation = carLocation;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	public String getLinetransportId() {
		return this.linetransportId;
	}

	public void setLinetransportId(String linetransportId) {
		this.linetransportId = linetransportId;
	}

	public Double getLocLongitude() {
		return this.locLongitude;
	}

	public void setLocLongitude(Double locLongitude) {
		this.locLongitude = locLongitude;
	}

	public Double getLocLatitude() {
		return this.locLatitude;
	}

	public void setLocLatitude(Double locLatitude) {
		this.locLatitude = locLatitude;
	}

	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	public Date getPurchaseTime() {
		return this.purchaseTime;
	}

	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public String getCarBrand() {
		return this.carBrand;
	}

	public void setCarBrand(String carBrand) {
		this.carBrand = carBrand;
	}

	public String getStorage() {
		return this.storage;
	}

	public void setStorage(String storage) {
		this.storage = storage;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public String getTerminalId() {
		return terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	
}
