package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Cityline generated by hbm2java
 */
@Component
public class Cityline implements java.io.Serializable {

	private String id;
	private String cityName;
	private Float refPrice;
	private Date relDate;
	private String carrierId;
	private String VIPService;
	private String name;
	private String detailPrice;
	private String remarks;
	private String VIPDetail;

	public String getVIPDetail() {
		return VIPDetail;
	}

	public void setVIPDetail(String vIPDetail) {
		VIPDetail = vIPDetail;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVIPService() {
		return VIPService;
	}

	public void setVIPService(String vIPService) {
		VIPService = vIPService;
	}

	public Cityline() {
	}

	public Cityline(String id) {
		this.id = id;
	}

	

	public Cityline(String id, String cityName, Float refPrice, Date relDate,
			String carrierId, String vIPService, String name,
			String detailPrice, String remarks, String vIPDetail) {
		super();
		this.id = id;
		this.cityName = cityName;
		this.refPrice = refPrice;
		this.relDate = relDate;
		this.carrierId = carrierId;
		VIPService = vIPService;
		this.name = name;
		this.detailPrice = detailPrice;
		this.remarks = remarks;
		this.VIPDetail = vIPDetail;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Float getRefPrice() {
		return this.refPrice;
	}

	public void setRefPrice(Float refPrice) {
		this.refPrice = refPrice;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	

	public String getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(String detailPrice) {
		this.detailPrice = detailPrice;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
