package cn.edu.bjtu.vo;

// Generated 2015-2-24 14:26:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Assessform generated by hbm2java
 */
@Component
public class Comment implements java.io.Serializable {

	private String id;
	private String clientId;
	private Date relDate;
	private String orderId;
	private String serviceAttitude;
	private String transportEfficiency;
	private String cargoSafety;
	private String totalMoney;
	private String comment;
	private Integer linetransport;
	private Integer cityline;
	private Integer car;
	private Integer warehouse;
	
	private String carrierId;//add by haochendong 

	public Comment() {
	}
	
	

	public String getCarrierId() {
		return carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}



	public Comment(String id) {
		this.id = id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	

	public String getServiceAttitude() {
		return serviceAttitude;
	}



	public void setServiceAttitude(String serviceAttitude) {
		this.serviceAttitude = serviceAttitude;
	}



	public String getTransportEfficiency() {
		return transportEfficiency;
	}



	public void setTransportEfficiency(String transportEfficiency) {
		this.transportEfficiency = transportEfficiency;
	}



	public String getCargoSafety() {
		return cargoSafety;
	}



	public void setCargoSafety(String cargoSafety) {
		this.cargoSafety = cargoSafety;
	}



	public String getTotalMoney() {
		return totalMoney;
	}



	public void setTotalMoney(String totalMoney) {
		this.totalMoney = totalMoney;
	}



	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getLinetransport() {
		return this.linetransport;
	}

	public void setLinetransport(Integer linetransport) {
		this.linetransport = linetransport;
	}

	public Integer getCityline() {
		return this.cityline;
	}

	public void setCityline(Integer cityline) {
		this.cityline = cityline;
	}

	public Integer getCar() {
		return this.car;
	}

	public void setCar(Integer car) {
		this.car = car;
	}

	public Integer getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Integer warehouse) {
		this.warehouse = warehouse;
	}

}
