package cn.edu.bjtu.vo;

// Generated 2015-2-14 19:50:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GoodsClientViewId generated by hbm2java
 */
public class FeedbackGoodsView implements java.io.Serializable {

	private String id;
	private String goodsId;
	private String name;
	private String recieverId;
	private String recieverStatus;
	private String recieverFile;
	private Date relDate;

	public FeedbackGoodsView() {
	}

	public FeedbackGoodsView(String id) {
		this.id = id;
	}

	public FeedbackGoodsView(String id, String goodsId, String name, String recieverId,
			String recieverStatus, String recieverFile, Date relDate) {
		this.id = id;
		this.goodsId = goodsId;
		this.name = name;
		this.recieverId = recieverId;
		this.recieverStatus = recieverStatus;
		this.recieverFile = recieverFile;
		this.relDate = relDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getRecieverId() {
		return this.recieverId;
	}

	public void setRecieverId(String recieverId) {
		this.recieverId = recieverId;
	}
	
	public String getRecieverStatus() {
		return this.recieverStatus;
	}

	public void setRecieverStatus(String recieverStatus) {
		this.recieverStatus = recieverStatus;
	}
	
	public String getRecieverFile() {
		return this.recieverFile;
	}

	public void setRecieverFile(String recieverFile) {
		this.recieverFile = recieverFile;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

}
