package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Goodsform generated by hbm2java
 */
public class Feedbackform implements java.io.Serializable {

	private String id;
	private String goodsId;
	private String recieverId;
	private String recieverStatus;
	private String recieverFile;

	public Feedbackform() {
	}

	public Feedbackform(String id) {
		this.id = id;
	}

	public Feedbackform(String id, String goodsId, String recieverId,
			String recieverStatus, String recieverFile) {
		this.id = id;
		this.goodsId = goodsId;
		this.recieverId = recieverId;
		this.recieverStatus = recieverStatus;
		this.recieverFile = recieverFile;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getRecieverId() {
		return this.recieverId;
	}

	public void setRecieverId(String recieverId) {
		this.recieverId = recieverId;
	}

	public String getRecieverStatus() {
		return this.recieverStatus;
	}

	public void setRecieverStatus(String recieverStatus) {
		this.recieverStatus = recieverStatus;
	}

	public String getRecieverFile() {
		return this.recieverFile;
	}

	public void setRecieverFile(String recieverFile) {
		this.recieverFile = recieverFile;
	}

}
