package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Attention generated by hbm2java
 */
@Component
public class Focus implements java.io.Serializable {

	private String id;
	private String clientId;
	private String focusType;//关注的资源类型
	private String focusId;//资源id
	private String status;//关注状态

	public Focus() {
	}

	public Focus(String id) {
		this.id = id;
	}

	public Focus(String id, String clientId, String focusType,
			 String focusId, String status) {
		this.id = id;
		this.clientId = clientId;
		this.focusType = focusType;
		this.focusId = focusId;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getFocusType() {
		return this.focusType;
	}

	public void setFocusType(String focusType) {
		this.focusType = focusType;
	}

	public String getFocusId() {
		return this.focusId;
	}

	public void setFocusId(String focusId) {
		this.focusId = focusId;
	}
	
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
