package cn.edu.bjtu.vo;

// Generated 2015-2-22 16:45:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * CarCarrierViewId generated by hbm2java
 */
@Component
public class FocusCompanyView implements java.io.Serializable {

	private String id;
	private String clientId;
	private String focusType;
	private String focusId;
	private String status;
	private String companyName;
	private Date relDate;
	private String carrierId;// add by RussWest0 at 2015年6月12日,下午1:19:07 
	
	
	public String getCarrierId() {
		return carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public FocusCompanyView() {
	}

	public FocusCompanyView(String id) {
		this.id = id;
	}

	public FocusCompanyView(String id, String clientId, String focusType,
			String focusId, String status,
			String companyName, Date relDate) {
		this.id = id;
		this.clientId = clientId;
		this.focusType = focusType;
		this.focusId = focusId;
		this.status = status;
		this.companyName = companyName;
		this.relDate = relDate;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getFocusType() {
		return this.focusType;
	}

	public void setFocusType(String focusType) {
		this.focusType = focusType;
	}

	public String getFocusId() {
		return this.focusId;
	}

	public void setFocusId(String focusId) {
		this.focusId = focusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
