package cn.edu.bjtu.vo;

import java.util.Date;

import org.springframework.stereotype.Component;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

/**
 * Linetransport generated by hbm2java
 */
@Component
public class Linetransport implements java.io.Serializable {

	private String id;
	private String startPlace;
	private String endPlace;
	private int onWayTime;
	private Float refPrice;
	private Date relDate;
	private String carrierId;
	private String detailPrice;
	private String remarks;
	private String type;
	private String lineName;

	public Linetransport() {
	}

	public Linetransport(String id) {
		this.id = id;
	}

	

	public Linetransport(String id, String startPlace, String endPlace,
			int onWayTime, Float refPrice, Date relDate, String carrierId,
			String detailPrice, String remarks, String type, String lineName) {
		super();
		this.id = id;
		this.startPlace = startPlace;
		this.endPlace = endPlace;
		this.onWayTime = onWayTime;
		this.refPrice = refPrice;
		this.relDate = relDate;
		this.carrierId = carrierId;
		this.detailPrice = detailPrice;
		this.remarks = remarks;
		this.type = type;
		this.lineName = lineName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStartPlace() {
		return this.startPlace;
	}

	public void setStartPlace(String startPlace) {
		this.startPlace = startPlace;
	}

	public String getEndPlace() {
		return this.endPlace;
	}

	public void setEndPlace(String endPlace) {
		this.endPlace = endPlace;
	}

	
	public int getOnWayTime() {
		return onWayTime;
	}

	public void setOnWayTime(int onWayTime) {
		this.onWayTime = onWayTime;
	}

	public Float getRefPrice() {
		return this.refPrice;
	}

	public void setRefPrice(Float refPrice) {
		this.refPrice = refPrice;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public String getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(String detailPrice) {
		this.detailPrice = detailPrice;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLineName() {
		return this.lineName;
	}

	public void setLineName(String lineName) {
		this.lineName = lineName;
	}
}
