package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Attention generated by hbm2java
 */
@Component
public class Message implements java.io.Serializable {

	private String id;
	private String clientId;
	private String content;
	private Date relDate;

	public Message() {
	}

	public Message(String id) {
		this.id = id;
	}

	public Message(String id, String clientId, String content, Date relDate) {
		this.id = id;
		this.clientId = clientId;
		this.content = content;
		this.relDate = relDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}
	

}
