package cn.edu.bjtu.vo;

import org.springframework.stereotype.Component;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

/**
 * Userinfo generated by hbm2java
 */@Component
public class Userinfo implements java.io.Serializable {

	private String id;
	private String username;
	private String password;
	private String phone;
	private String privilege;
	private int userKind;
	private String hostAccount;
	private String status;
	private String subAccountStatus;
	private String email;
	
	public Userinfo() {
	}

	public Userinfo(String id) {
		this.id = id;
	}

	

	
	
	public Userinfo(String id, String username, String password, String phone,
			String privilege, int userKind, String hostAccount, String status,
			String subAccountStatus, String email) {
		super();
		this.id = id;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.privilege = privilege;
		this.userKind = userKind;
		this.hostAccount = hostAccount;
		this.status = status;
		this.subAccountStatus = subAccountStatus;
		this.email = email;
	}

	public int getUserKind() {
		return userKind;
	}

	public void setUserKind(int userKind) {
		this.userKind = userKind;
	}

	public String getHostAccount() {
		return hostAccount;
	}

	public void setHostAccount(String hostAccount) {
		this.hostAccount = hostAccount;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSubAccountStatus() {
		return subAccountStatus;
	}

	public void setSubAccountStatus(String subAccountStatus) {
		this.subAccountStatus = subAccountStatus;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(String privilege) {
		this.privilege = privilege;
	}

}
